### ISSUE TITLE
cloudatcost is not a recognized provider

### ISSUE THREAD

**Issue by voobscout** [fog/fog-cloudatcost#15]
``` ruby
require 'fog'
compute = Fog::Compute.new(
  provider: 'CloudAtCost',
  api_key: 'coolapikey',
  email: 'some@where.com'
)
```

produces:

```
ArgumentError: cloudatcost is not a recognized provider
from /path_to_rvm_ruby/gems/fog-core-1.35.0/lib/fog/core/services_mixin.rb:12:in `new'
```

ruby 2.1.8p440 (2015-12-16 revision 53160) [x86_64-linux]
installed fog, fog-cloudatcost fresh from gems

**Comment by h0lyalg0rithm** [comment]
@geemus Could you please release a new version of fog-core to fix the issue.Thanks

**Comment by geemus** [comment]
Yeah, I can try to get to that soon, sorry for the delay. Could you add me to the gem owners on rubygems.org? That way I can do updates just-in-case? Thanks!

**Comment by h0lyalg0rithm** [comment]
@geemus Done I have added you. :+1:

**Comment by geemus** [comment]
Thanks!

**Comment by geemus** [comment]
Should be good to go now, just released fog-core 1.36.0. Thanks!

**Comment by h0lyalg0rithm** [comment]
@geemus Thanks a lot :+1:

**Comment by h0lyalg0rithm** [comment]
@voobscout Please update your gemfile to use the latest version of the gem, its should work now

**Comment by voobscout** [comment]
@h0lyalg0rithm @geemus Thanks! It works now.
